main:
  - identifier: home
    name: Home
    url: /
    weight: 10

  - identifier: archives
    name: Archives
    url: /posts/
    weight: 20

  - identifier: tags
    name: Tags
    url: /tags/
    weight: 30

  - identifier: categories
    name: Categories
    url: /categories/
    weight: 40
